# Generated by Django 3.0.6 on 2020-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
