# Generated by Django 3.0.6 on 2020-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200510_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='test bio', max_length=200),
            preserve_default=False,
        ),
    ]
