# Generated by Django 3.0.6 on 2020-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20200510_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
