# Generated by Django 3.0.6 on 2020-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200510_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
