# Generated by Django 3.0.6 on 2020-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200508_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='blog/bg_1.jpg', upload_to='blog'),
            preserve_default=False,
        ),
    ]
