# Generated by Django 3.0.6 on 2020-05-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.CharField(default='Mother', max_length=200),
            preserve_default=False,
        ),
    ]
