# Generated by Django 3.0.6 on 2020-05-15 17:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0008_auto_20200510_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.UserProfile')),
            ],
        ),
    ]
