# Generated by Django 3.0.6 on 2020-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200515_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promote_image',
            field=models.ImageField(default='course-1.jpg', upload_to='courses'),
            preserve_default=False,
        ),
    ]
