# Generated by Django 3.0.6 on 2020-05-15 18:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='history',
            field=ckeditor.fields.RichTextField(default='some text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='school_info',
            field=ckeditor.fields.RichTextField(default='some other text'),
            preserve_default=False,
        ),
    ]
