# Generated by Django 3.0.6 on 2020-05-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_position'),
        ('about', '0002_auto_20200515_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review'),
            preserve_default=False,
        ),
    ]
