# Generated by Django 3.0.6 on 2020-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_position'),
        ('about', '0003_company_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reviews',
        ),
        migrations.AddField(
            model_name='company',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
