# Generated by Django 3.0.6 on 2020-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fb_link',
            field=models.CharField(default='#', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_link',
            field=models.CharField(default='1', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_link',
            field=models.CharField(default='#', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
