# Generated by Django 3.0.6 on 2020-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200516_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fb_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
