# Generated by Django 3.0.6 on 2020-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20200516_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_awards',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_students',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
