# Generated by Django 3.0.6 on 2020-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200516_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='promotion_video',
            field=models.CharField(default='https://vimeo.com/45830194', max_length=200),
            preserve_default=False,
        ),
    ]
