# Generated by Django 3.0.6 on 2020-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_company_promotion_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='promotion_video',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
